import turtle
import time
import keyboard
import pdb
import datetime
print("DoodleThon Alpha.1f")
now= datetime.datetime.now()
print("Current date and EST:", now)
screen=turtle.Screen()
screen.setup(width=800, height=700)
t=turtle.Turtle()
t.shape("circle")
t.color("blue")
time.sleep(1)
t.speed(9)
t.begin_fill()
t.forward(300)
t.setheading(90)
t.forward(225)
t.setheading(180)
t.forward(300)
t.setheading(270)
t.forward(175)
t.end_fill()
t.color("Yellow")
t.begin_fill()
t.setheading(45)
t.forward(160)
t.setheading(135)
t.forward(160)
t.setheading(270)
t.forward(175)
t.end_fill()
print("loaded")
time.sleep(2)
t.reset()
d=turtle.Turtle()
d.pensize(5)
d.shape("square")
d.speed(50)
print("Here is the tutorial for this Doodle Program")
print("use your mouse to doodle. You can also use it to click and doodle as well!")
print("Use space to erase. I will shine red for 2 seconds before you can erase, showing its location.")
print("Use number keys 1 to 6 to change colors and stop erasing. We currently have 6 colors, red, blue, green, yellow, black, and pink.")
print("Press S to save")
print("Press keys B, and E to begin and end filling a space")
print("Use X key to reset doodle, and T key to change the thickness of your pen!")
def drag_handler(x, y):
    d.ondrag(None) 
    d.setheading(d.towards(x, y)) 
    d.goto(x, y) 
    d.ondrag(drag_handler)       
def change_color_red():
    d.color("red")
    print("Pen red")
def change_color_blue():
    d.color("blue")
    print("Pen blue")
def change_color_green():
    d.color("green")
    print("Pen green")
def change_color_yellow():
    d.color("yellow")
    print("Pen yellow")
def change_color_black():
    d.color("black")
    print("Pen black")
def change_color_pink():
    d.color("pink")
    print("Pen pink")
def change_color_white():
        d.color("red")
        time.sleep(1.1)
        d.color("white")
        print("Eraser On")
def thickness():
   cjk=int(input("how thick do you want your pen:"))
   d.pensize(cjk)
   print(cjk)
   if cjk<1:
       d.pensize(1)
       print("1 IS THE MINIMUM THICKNESS FOR YOUR PEN")
   if cjk>30:
       print("ERM ARE YOU CASEOH???")
       print("30 IS THE MAX THICKNESS FOR THE PEN!")
       d.pensize(30)
def delete():
    d.reset()
    print("Doodle Reset")
    d.speed(50)
    d.pensize(5)
def move_pen_to_click(x,y):
    d.penup()
    d.goto(x,y)
    d.pendown()
def save_art():
    canvas = turtle.getcanvas()
    canvas.postscript(file="drawing.eps")
    print("Doodle saved")
def begin_fill():
    d.begin_fill()
    print("Filling")
def end_fill():
    d.end_fill()
    print("Filled")
screen.onkey(change_color_red,"1")  
screen.onkey(change_color_blue,"2")  
screen.onkey(change_color_green,"3")
screen.onkey(change_color_yellow, "4") 
screen.onkey(change_color_black, "5")  
screen.onkey(change_color_pink, "6")
screen.onkey(change_color_white, "space")
screen.onkey(delete,"x")
screen.onkey(thickness,"t")
screen.onkey(save_art,"s")
screen.onkey(begin_fill,"b")
screen.onkey(end_fill,"e")
turtle.Screen().onscreenclick(move_pen_to_click)
screen.listen()
d.ondrag(drag_handler)
turtle.done()   
